# Generated by Django 6.1 on 2026-09-02 02:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_schoolclass_section_classsection_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text="Short code, e.g. 'UT1', 'FST', 'MAIN'", max_length=20)),
                ('name', models.CharField(help_text="e.g. 'Unit Test 1'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sequence_order', models.PositiveIntegerField(default=0, help_text='Display/sort order within the academic year')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'sequence_order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.classsection')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['exam', 'class_section', 'subject'],
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='exams_unique_code_per_year'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'class_section', 'subject'), name='exams_unique_exam_class_section_subject'),
        ),
    ]
