# Generated by Django 6.1 on 2026-09-02 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='passing_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. When set, enables pass/fail on the marksheet for this subject. Left null for exams where no passing threshold applies.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
