# Generated by Django 6.1 on 2026-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.CharField(default='Kathwada High School', max_length=200)),
                ('label', models.CharField(help_text="e.g. '2026-27'", max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='academics_one_current_year_per_school'), models.UniqueConstraint(fields=('school', 'label'), name='academics_unique_label_per_school'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academics_end_date_after_start_date')],
            },
        ),
    ]
