# Generated by Django 6.1 on 2026-08-29 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'Std 10'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display/sort order (e.g. 1 for Std 1, 10 for Std 10), independent of name text.')),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='academics_unique_class_name')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'A'", max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='academics_unique_section_name')],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections_led', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='academics.section')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'school_class__order', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code, e.g. 'MATH'", max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='academics_unique_subject_name'), models.UniqueConstraint(fields=('code',), name='academics_unique_subject_code')],
            },
        ),
        migrations.CreateModel(
            name='ClassSectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='academics.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_section_links', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='subjects',
            field=models.ManyToManyField(related_name='class_sections', through='academics.ClassSectionSubject', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='classsectionsubject',
            constraint=models.UniqueConstraint(fields=('class_section', 'subject'), name='academics_unique_class_section_subject'),
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('school_class', 'section', 'academic_year'), name='academics_unique_class_section_per_year'),
        ),
    ]
